# Generated by Django 5.2.6 on 2025-09-12 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_doctor_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResultsLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'الاستعلام عن التحليل',
                'verbose_name_plural': 'الاستعلام عن التحليل',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم التحليل')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='الوحدة')),
                ('reference_range', models.CharField(blank=True, max_length=50, verbose_name='المدى المرجعي')),
                ('description', models.TextField(blank=True, verbose_name='وصف التحليل')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='سعر التحليل')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testcatalogs', to=settings.AUTH_USER_MODEL, verbose_name='صاحب التحليل')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_requests', to='patients.doctor', verbose_name='الدكتور')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to='patients.patient', verbose_name='المريض')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to='analyses.testcatalog', verbose_name='نوع التحليل')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=255, verbose_name='النتيجة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت التحليل')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='patients.patient', verbose_name='المريض')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyses.testcatalog', verbose_name='نوع التحليل')),
            ],
        ),
        migrations.CreateModel(
            name='TodaysAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False, verbose_name='تم التنفيذ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='todays_analysis', to='analyses.analysisrequest', verbose_name='طلب التحليل')),
            ],
        ),
    ]
