# Generated by Django 5.2.6 on 2025-09-18 11:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'verbose_name': 'التحليل', 'verbose_name_plural': 'التحاليل'},
        ),
        migrations.AlterModelOptions(
            name='analysisrequest',
            options={'verbose_name': 'طلب تحليل', 'verbose_name_plural': 'طلبات التحليل'},
        ),
        migrations.RemoveField(
            model_name='analysisrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='analysisrequest',
            name='doctor',
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ ووقت الطلب'),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='قيمة الخصم'),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='نسبة الخصم'),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='السعر'),
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='analysisrequest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyses.testcatalog', verbose_name='نوع التحليل'),
        ),
    ]
