# Generated by Django 5.2.6 on 2025-09-11 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_testcatalog_user'),
        ('patients', '0004_doctor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_requests', to='patients.doctor', verbose_name='الدكتور')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to='patients.patient', verbose_name='المريض')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to='analyses.testcatalog', verbose_name='نوع التحليل')),
            ],
        ),
    ]
