# Generated by Django 5.2.6 on 2025-09-11 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_analysisrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodaysAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False, verbose_name='تم التنفيذ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='todays_analysis', to='analyses.analysisrequest', verbose_name='طلب التحليل')),
            ],
        ),
    ]
