# Generated by Django 5.2.6 on 2025-09-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_add_doctor_to_analysisrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcatalog',
            options={'verbose_name': 'كاتالوج التحاليل', 'verbose_name_plural': 'كتالوج التحاليل'},
        ),
        migrations.AlterModelOptions(
            name='todaysanalysis',
            options={'verbose_name': 'تحليل اليوم', 'verbose_name_plural': 'تحاليل اليوم'},
        ),
    ]
