# Generated by Django 5.2.6 on 2025-09-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0004_todaysanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='extra1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='قيمة إضافية 1'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='extra2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='قيمة إضافية 2'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='extra3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='قيمة إضافية 3'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='extra4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='قيمة إضافية 4'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='extra5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='قيمة إضافية 5'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='extra6',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='قيمة إضافية 6'),
        ),
    ]
