# Generated by Django 5.2.6 on 2025-09-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0005_analysis_extra1_analysis_extra2_analysis_extra3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='extra1',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='extra2',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='extra3',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='extra4',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='extra5',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='extra6',
        ),
        migrations.AddField(
            model_name='analysis',
            name='band',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Band'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='basophils',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Basophils'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='eosinophil',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Eosinophil'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='hct',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='HCT'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='hgb',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Hemoglobin (Hgb)'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='hgb_percent',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Hgb%'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='lymphocytes',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Lymphocytes'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='mch',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='MCH'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='mchc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='MCHC'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='mcv',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='MCV'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='monocytes',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Monocytes'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='neutrophils',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Neutrophils'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='plt',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Platelets (PLT)'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='rbcs',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Red blood cells (RBCs)'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='rdw_cv',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RDW-cv'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='segmented',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Segmented'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='wbc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='White blood cells (WBCs)'),
        ),
    ]
