# Generated by Django 5.2.6 on 2025-09-07 01:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('age', models.PositiveIntegerField(verbose_name='العمر')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='النوع')),
                ('national_id', models.CharField(blank=True, help_text='أرقام فقط', max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'يجب إدخال أرقام فقط بدون حروف')], verbose_name='الرقم القومي')),
                ('doctor_name', models.CharField(blank=True, max_length=100, verbose_name='اسم الدكتور')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
    ]
