# Generated by Django 5.2.6 on 2025-09-11 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الدكتور')),
                ('specialty', models.CharField(max_length=100, verbose_name='التخصص')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم التليفون')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.doctor', verbose_name='الدكتور'),
        ),
    ]
