# Generated by Django 5.2.6 on 2025-09-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_doctor_patient_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor_name',
        ),
    ]
