# Generated by Django 5.2.6 on 2025-09-19 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_doctor_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'الطبيب', 'verbose_name_plural': 'الأطباء'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'المريض', 'verbose_name_plural': 'المرضى'},
        ),
    ]
